CreateImageWizard: single upload_request
osbuild/image-builder-frontend pull request #102
Opened 2021-03-05 16:06 UTC by chloenayon

Change image_request to accept a single upload_request instead of
an array of upload_requests.

2021-03-08 10:38 UTC, Gundersanne commented
Nice! Adding blocked until the related composer PR is merged (osbuild/osbuild-composer#1267)

2021-03-09 09:39 UTC, Gundersanne requested changes
Because of #103  this needs a rebase now

2021-03-09 09:39 UTC, Gundersanne commented on src/SmartComponents/CreateImageWizard/CreateImageWizard.js
> +                        upload_request: [ this.state.uploadAWS ],
This needs to not be an array now

2021-03-09 09:39 UTC, Gundersanne commented on src/SmartComponents/CreateImageWizard/CreateImageWizard.js
> +                        upload_request: [ upload_google ],
ditto

2021-03-09 11:03 UTC, chloenayon commented
made fixes to address @Gundersanne 's comments

2021-03-22 11:04 UTC, Gundersanne approved these changes

2021-03-22 11:04 UTC, merged