feat(HMS-3686): Update position of blueprint buttons
osbuild/image-builder-frontend pull request #1733
Opened 2024-03-04 14:18 UTC by avitova

This is a followup of #1631 and an update according to our new mockups. :)

2024-03-04 14:42 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +          {/*@ts-ignore*/}
Leftover I think, let's remove.

2024-03-04 14:45 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const [isOpen, setIsOpen] = useState<boolean>(false);
We don't need to specify `<boolean>` here, Typescript can infer it since the hook was initialized with `false`.

2024-03-04 14:48 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const [showDeleteModal, setShowDeleteModal] = React.useState(false);
`useState` has been imported, so you don't need to use `React.`.

2024-03-04 14:52 UTC, lucasgarfield requested changes
This is looking great! One oversight, the changes leaked out of experimental. Here's what I see running `npm run stage-beta`:

![image](https://github.com/osbuild/image-builder-frontend/assets/95542540/308d0270-a7c6-45e2-815e-030bfac892c1)

You'll just need to put all of this behind the experimental flag. You can use conditional rendering like so: `{experimentalFlag && ... }`... you should be able to find plenty of examples of this in the code already.

2024-03-04 15:45 UTC, avitova commented
Thank you for your review @lucasgarfield 
I have rebased, addressed the comments, fixed a small bug (when deleting a blueprint, we should set the selectedBlueprint to undefined), and put back the Create image button since that is needed out of experimental. :)

2024-03-04 17:03 UTC, lucasgarfield requested changes
Thanks for the updates! I have some opinionated nitpicks next. I’m trying not to block on things that are too nitpicky but I think these won’t be too hard and should be worth it.

I would like to extract some of the JSX into new React components, and move some code (handlers and RTKQ hooks) deeper where it is closer to where it’s needed. This will help keep the scope of `<ImagesTable>` smaller, and keeping the handlers closer to where they called makes the code easier to read and understand. In general I try to avoid passing down props as much as possible, and since RTKQ hooks are cached I prefer to just call them in the component they’re needed in. So with that in mind, I hope you think these requests are reasonable. :sweat_smile:

2024-03-04 17:03 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const [buildBlueprint, { isLoading: imageBuildLoading }] =
We can move this into a new `<BlueprintActionsMenu>` component.

2024-03-04 17:03 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const onBuildHandler = async () => {
We can move this into a new `<BuildImagesButton>` component.

2024-03-04 17:03 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const [deleteBlueprint] = useDeleteBlueprintMutation({
We can move this to `<DeleteBlueprintModal>` I think.

2024-03-04 17:03 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const handleDelete = async () => {
We can move this to `<DeleteBlueprintModal>` I think.

2024-03-04 17:03 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +  const onDeleteClose = () => {
We can move this to `<DeleteBlueprintModal>` I think.

2024-03-05 10:23 UTC, avitova commented
Thank you, Lucas, for the amount of suggestions. I think it all makes sense, and the code looks cleaner. All of the mentioned components are in a sense logical units, so I like the idea of not keeping this all in the images table. :) I decomposed based on your suggestion.

2024-03-05 10:49 UTC, lucasgarfield commented on src/Components/ImagesTable/ImagesTable.tsx
> +            )
This `)` is getting rendered to the right of the pagination :wink: 

![image](https://github.com/osbuild/image-builder-frontend/assets/95542540/08ff0743-1e4e-4691-99ed-1360e32989d2)

2024-03-05 10:52 UTC, lucasgarfield commented
Thanks for refactoring, @avitova! This looks really nice! 

Please just fix the tiny bug with the `)` I mentioned and I'll approve and merge.

We will probably also need to do a follow-up and convert these components to use the Redux store when https://github.com/osbuild/image-builder-frontend/pull/1712 gets merged.

2024-03-05 11:11 UTC, lucasgarfield approved these changes
Thank you!

2024-03-05 12:49 UTC, merged