ci(HMS-3962): Update Integration test image for IQE
osbuild/image-builder-frontend pull request #2113
Opened 2024-06-03 10:17 UTC by akhil-jha

2024-06-03 10:18 UTC, akhil-jha commented
@jrusz

2024-06-04 07:34 UTC, jrusz requested changes
One small change requested + please add a description to you commit to make the "best practices" check happy.

2024-06-04 07:34 UTC, jrusz commented on deploy/iqe-trigger-integration.yml
> +  value: quay.io/cloudservices/iqe-tests
```suggestion
  value: quay.io/cloudservices/iqe-tests:insights-experiences
```
Same as in image-builder repo, let's add the tag here.

2024-06-04 08:52 UTC, regexowl commented
/retest

2024-06-07 07:51 UTC, regexowl commented
/retest

2024-06-07 08:04 UTC, jrusz approved these changes

2024-06-07 08:10 UTC, merged