imageTable: link images to parent blueprint <HMS-4353>
osbuild/image-builder-frontend pull request #2268
Opened 2024-07-23 12:27 UTC by mgold1234

this commit add link to parent blueprint from specific image

2024-07-23 13:08 UTC, ezr-ondrej requested changes
I'm not sure we need to fetch all the data for this, I believe we do have all data we need.

Few thoughts:

1. I don't think we need to use Link component from react router, that has a purpose of redirecting to different ract-router managed page, which we don't do here, we are staying on the same page.
2. I believe we have the blueprint_id in compose here, we could use that instead of fetching it in the handleClick function.
3. We should ideally make it optional, so ad-hoc images (composes) that do not have blueprint_id, do not have this link, that would fail

Here is a rough example (not working code) what I mean:

```jsx
import { Button } from '@patternfly/core'
// ......

// might not even need to be a separate function and might be inlined
const handleClick = (blueprintId) => { dispatch(setBlueprintId(blueprintId)) }

// ..... 

{compose.blueprint_id && (
  <Button variant="link" onClick={(_evt) => handleClick(compose.blueprint_id)}>
    {compose.image_name || compose.id}
  </Button>{' '}
) || ({compose.image_name || compose.id})
```

2024-07-24 08:05 UTC, regexowl reviewed
Looks very nice! Added some nit picks :)

2024-07-24 08:05 UTC, regexowl commented on src/Components/ImagesTable/ImagesTable.tsx
> +  }) => {
We already have a type for blueprintId, can we use that?

```suggestion
  const handleClick = ({
    blueprintId,
  }: {
    blueprintId: BlueprintItem['id'];
  }) => {
```

2024-07-24 08:05 UTC, regexowl commented on src/Components/ImagesTable/ImagesTable.tsx
> +            onClick={() => handleClick({ blueprintId: compose.blueprint_id })}
Maybe we should render the name as a button only when the image is connected to a blueprint? When the blueprint id is undefined, we should probably just do plain text. What do you think?

Currently when you have "orphan" image it's name is a link, but it doesn't do anything when clicking on it:
![image](https://github.com/user-attachments/assets/5eeb6b59-5f69-4f5f-bbbd-3c5a9f6d94db)

2024-07-24 15:17 UTC, ezr-ondrej commented
/retest

2024-07-24 19:23 UTC, mgold1234 commented
/retest

2024-07-25 06:28 UTC, regexowl commented
/retest

2024-07-25 07:35 UTC, merged