Wizard: add partitioning modes into file system config
osbuild/image-builder-frontend pull request #2342
Opened 2024-08-12 13:21 UTC by ondrejbudai

The image builder API supports partitioning modes for a while. Currently, the frontend doesn't specify one, which makes the backend default to "auto-lvm". This partitions the image as lvm if the request contains an extra mountpoint that isn't specified in the base partition table. Otherwise, it's raw-partitioned. In other words, it's confusing.

This commit gives users an option to specify the mode explicitly: either to lvm, or raw. This should reduce confusion and give users more power.

The partitioning mode is now enforced by the frontend. This means that old blueprints are "converted" when edited: A simple heurestic is in charge of that: if there's a custom mountpoint in the original blueprint, the mode is set to lvm. Otherwise, it defaults to raw.

TODO:

- [ ] Discuss this with the UX folks.
- [ ] Add some tests (I will need help with this part :sweat_smile: ).

There's also one extra unfortunate thing: There's already a property called `FileSystemPartitionMode` in the code used to control whether the partitioning is manual, or automatic. Unfortunately, the API property for lvm/raw is called a partitioning mode, so this creates a lot of confusion. I guess we should rename the original "partition mode" to prevent this clash. Suggestions are welcome!

2024-08-12 13:50 UTC, regexowl commented
> There's also one extra unfortunate thing: There's already a property called `FileSystemPartitionMode` in the code used to control whether the partitioning is manual, or automatic. Unfortunately, the API property for lvm/raw is called a partitioning mode, so this creates a lot of confusion. I guess we should rename the original "partition mode" to prevent this clash. Suggestions are welcome!

We can do that for sure! The hardest part will be coming up with a new name, but something like `FileSystemConfigurationMode` might work? Or just `fscMode`, it's a value only for us so the key will be finding something that won't get mixed up with the partitioning mode :thinking:

2024-08-27 12:50 UTC, regexowl commented
Getting back to this a bit later, sorry about that :sweat: How can we move this forward?

A rebase to resolve the conflicts will be needed, previously used `FileSystemPartitionMode` was renamed to `FileSystemConfigurationType` which should make the naming less confusing. Some linting errors will need to be resolved as well.

I agree some tests would be nice, I can put something together for sure and try to add them in a new commit here. Or walk you through the tests if you'd like. Whatever works best.

2024-09-26 08:13 UTC, regexowl requested changes
@ondrejbudai This looks great! Thank you! Could you please rebase and resolve lint errors? `npm run lint:js:fix` should be able to do all the work. I can then take over and either try to add some tests in this PR or better open a follow up.

Should we maybe gate this behind a feature flag for some time? To make this available in beta only? What do you think @lucasgarfield

2024-09-26 08:13 UTC, regexowl commented on src/Components/CreateImageWizard/steps/FileSystem/FileSystemConfiguration.tsx
> +            description="Filesystems will be created directly on top of physical partitions"
I believe this was feedback on the UX call.

```suggestion
            description="File systems will be created directly on top of physical partitions"
```

2024-11-05 11:27 UTC, ondrejbudai commented
Closing this, we decided to re-implement the partitioning on the backend, so let's wait for it, and then implement it in the frontend.

2024-11-05 11:27 UTC, closed without merging