Adds icons and text strings for image build status
osbuild/image-builder-frontend pull request #45
Opened 2020-11-06 14:00 UTC by jgiardino

This update provides a status component that replaces the [raw status value](https://github.com/osbuild/osbuild-composer/blob/master/internal/cloudapi/openapi.yml#L84) with an icon and text string depending on the status value provided. The icon and text are based on [examples in the design](https://docs.google.com/presentation/d/1YUPsj01oafTfnTqlihf6-stGbuINfQSIN9K9a24-byY/edit#slide=id.g9551495f59_6_0). An example of each status state is shown in the example below. 

Some notes:
- One difference between this implementation and the design is that the design shows a link to get an error code for the failed status, but this link should be added after support for this exists.
- This status component is specific to images that are uploaded, which is what we initially plan to support. When support for downloading images is provided, it should be updated to provide the status we would show for downloadable images.

Closes #34 

![image](https://user-images.githubusercontent.com/21063328/98373442-3fae8e00-200d-11eb-98be-034343df7075.png)

2020-11-06 14:05 UTC, jgiardino commented
@Gundersanne @jkozol - I haven't added anything to tests for this component. Do you have any suggestions on what should be tested? And would this test be in the context of LandingPage.test.js?

@katierik @andreasn - Will you review the example I posted and let me know if the various messages in the Status column match what you were expecting?

2020-11-09 16:59 UTC, Gundersanne commented
@jgiardino I pushed a commit to your branch, adding a test and rebasing it to include the extra tests.

2020-11-09 17:39 UTC, katierik commented
@jgiardino In the screenshot its hard to tell - is the processing indicator animated?

2020-11-09 17:45 UTC, Gundersanne commented
@katierik yup, it's a spinner thingy

2020-11-09 17:46 UTC, katierik commented
Then I'm 👍

2020-11-10 10:34 UTC, andreasn commented
Looks good to me!

2020-11-10 12:16 UTC, atodorov requested changes
Other than the location of the test file the tests look good to me.

2020-11-10 12:16 UTC, atodorov commented on src/test/SmartComponents/LandingPage/ImagesTable.test.js
> +import React from 'react';
File name should be SmartComponents/ImagesTable/ImagesTable.test.js IMO.

2020-11-11 10:51 UTC, atodorov approved these changes
Test LGTM, feel free to merge.

2020-11-12 09:58 UTC, merged