tests: Redo waiting for elements to be removed to resolve warning
osbuild/image-builder-frontend pull request #57
Opened 2020-11-24 14:02 UTC by atodorov

gets rid of:

Warning: You seem to have overlapping act() calls, this is not
supported. Be sure to await previous act() calls before making a
new one.

2020-11-24 16:29 UTC, Gundersanne approved these changes

2020-11-24 16:30 UTC, Gundersanne requested changes
Thank you! Just remove the lines tbh, no need to comment them out.

2020-11-24 16:30 UTC, Gundersanne commented on src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
> +        // const p2 = waitForElementToBeRemoved(() => screen.queryByTestId('subscription-activation'));
Just remove this line

2020-11-24 16:30 UTC, Gundersanne commented on src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
> +        // await p2;
and this one, no need to comment them out, just remove

2020-11-25 10:54 UTC, atodorov commented
> Thank you! Just remove the lines tbh, no need to comment them out.

Thanks for catching this. All updated.

2020-11-25 11:07 UTC, Gundersanne approved these changes
ay nice, thanks!

2020-11-25 11:07 UTC, merged